spring:
  application:
    name: azure-services-lab-springboot

  ### [ spring.config.import ]
  ### - client-secret 을 소스 상에 하드코딩하지 않고 실행 환경 내 별도 파일로 관리하는 경우 사용
  ###     -> 파일 기반이 아닌 환경 변수, 또는 `-Dspring.data.redis.azure.credential.client-secret` argument 로
  ###        client-secret 을 전달하는 경우에는 불필요함
  ### - `optional:configtree:(client-secret 파일 경로)` 형식으로 (client-secret 파일 경로) 까지만 지정 -> 파일명은 제외
  ###     -> OS 별 속성에 맞게 'C:/workspace' (윈도우), '/home/app' (리눅스) 와 같이 파일 경로를 지정해야 함
  ###     -> client-secret 파일명은 하단 client-secret 속성에서 지정함
  # config:
  #   import: optional:configtree:(client-secret 파일 경로)

  ### [ spring-boot-starter-data-redis 전용 설정 ]
  data:
    redis:
      host: (Azre Managed Redis URL)
      ### Azure Managed Redis 의 port, 고정값 `10000` 지정
      port: 10000
      ### [ Azure Managed Redis ACL (Access Control List) 에 설정된 username ]
      ### - Azure Managed Redis 의 Authentication -> Redis Users -> Username 에서 정확한 값을 확인 후 설정할 것
      ### - Service Principal/Managed Identity 의  Object ID 나 Principal ID 등과 혼동하지 말 것
      username: (Azure Managed Redis ACL username)
      ### Redis 에 대한 연결을 기다리는 최대 시간. 필요시 수정할 것
      connect-timeout: 10s
      ### Redis 명령 응답을 기다리는 최대 시간. 필요시 수정할 것
      timeout: 10s
      ssl:
        enabled: true
      azure:
        ### Microsoft Entra ID 인증 기반 인증 -> password 불필요
        passwordless-enabled: true
        profile:
          tenant-id: (Azure Tenant ID)
        credential:
          ########## Service Principal + client-secret 설정 ##########
          ### [ Azure credential :: client ID ]
          ### - Microsoft Entra 앱 등록 (App Registration) 에서 조회한 해당 Service Principal 의 Application (client) ID
          client-id: (Service Principal Application client ID)

          ### [ Azure credential :: client secret ]
          ### - Microsoft Entra 앱 등록 (App Registration) 에서 생성한 Secret
          ### - (Case 1.) 실행 환경 내 별도 파일로 client-secret 을 전달
          ###     -> 상단 `spring.config.import` 로 지정한 경로에 위치한 파일명을 아래 예제와 같이 지정
          # client-secret: ${azure-service-principal-client-secret-01.txt}
          ### - (Case 2.) `-Dspring.data.redis.azure.credential.client-secret` argument 로 jar 실행시 전달
          ###     -> yaml 설정 내에 client-secret 속성 지정할 필요 없음
          ### - (Case 3.) `AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET` 환경변수로 client-secret 을 전달
          client-secret: ${AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET}

          ########## Service Principal + client-certificate 설정 ##########
          ### [ Azure credential :: client certificate path ]
          ### - Service Principal 에 등록된 PEM 또는 PFX 인증서 경로.
          ### - 경로는 Secret 이 아니므로 하드코딩 가능
          # client-certificate-path: (/path/to/service-principal-certificate.pem)

          ### [ Azure credential :: client certificate password ]
          ### - PFX 인증서의 비밀번호, PEM 인증서를 사용하는 경우 이 속성은 생략 가능
          ### - 하단 설정은 `AZURE_SERVICE_PRINCIPAL_CERTIFICATE_PASSWORD` 환경변수로 password 를 전달
          # client-certificate-password: ${AZURE_SERVICE_PRINCIPAL_CERTIFICATE_PASSWORD:}

### [ application.azure.managed-redis ]
### - 해당 설정은 SpringBoot 공식 설정이 아닌, `Application 전용 Custom 설정`
###   필요시 application.azure.managed-redis 가 아닌 다른 설정으로 지정해도 무방함
application:
  azure:
    managed-redis:
      ########## Redis 전용 기본 TTL (duration, 만료 시간) 설정 ##########
      ### - Redis 는 key-vaule Data 저장시 TTL 을 설정하여 일정 시간 경과시 자동 삭제되게 할 수 있음
      ### - @see AzureManagedRedisStringClient.java
      ###   -> 명시적인 duration 없이 `save` 메서드 호출시 해당 duration 값이 자동 지정되도록 구현함
      ###   -> Redis 에 영구 저장되어야 하는 key-value 는 `savePermanently` 메서드를 사용해야 함
      ###   ->  `PT1800S` -> 예시 설정으로 30분(= 1800초)
      default-duration: PT1800S

      ########## Redis ACL 에 설정된 key-prefix 설정 ##########
      ### - key-prefix 는 하나의 Managed Redis 를 여러 애플리케이션이 공유할 때,
      ###   애플리케이션간 데이터 침범을 막기 위해 키 이름 앞에 붙이는 격리용 접두사입
      ### - Azure Managed Redis 는 Microsoft Entra ID 기반으로 인증되며,
      ###   각 Entra ID 별로 Redis ACL 에 설정된 key pattern 에 대해서만 접근 가능
      ###   따라서 이 prefix 값은 Redis ACL 의 key pattern 과 반드시 일치해야 함
      ### - @see AzureManagedRedisStringClient.java
      ###   -> key-prefix 가 적용된 기본적인 연동 예제를 구현함
      key-prefix: 'DEV:10000:AppName:'
